from constants.content import Content, ContentInfo
from constants.imgs import LOGO_WIDTH
from constants.paths import (
    ENV_FILE_PATH,
    MAIN_CSS_PATH,
    MAIN_HEADER_CSS_PATH,
    NAVIGATION_CSS_PATH,
    TUTORIAL_PDF_URL,
    TUTORIAL_VIDEO_URL,
    WHATSLAB_LOGO_URL,
    WONJU_LOGO_URL,
    YENSEI_ICON_URL,
)
from constants.text import BALANCEBALL_DESCRIPTION, DATABASE_DESCRIPTION, FITBOX_DESCRIPTION, TENNISBALL_DESCRIPTION, TUTORIAL_DESCRIPTION
